<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lottery.proto

namespace GPBMetadata;

class Lottery
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab0010a0d6c6f74746572792e70726f746f120e6c6f7474657279736572" .
            "76696365221b0a0a6c6f7474657279526571120d0a05706172616d180120" .
            "012809221a0a0a6c6f7474657279526573120c0a04646174611801200128" .
            "09324e0a074772656574657212430a076c6f7474657279121a2e6c6f7474" .
            "657279736572766963652e6c6f74746572795265711a1a2e6c6f74746572" .
            "79736572766963652e6c6f74746572795265732200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

